### PR TITLE
fix: Resolve nested relations

### LINKED ISSUE #63: Resolved Relations are not resolved themselves
## Expected Behavior

References in resolved relations are resolved as it is defined in the API request by parameter "resolved_relations".
We expected the same behaviour than in the [deprecated SDK where the resolved relations themselves](https://github.com/storyblok/storyblok-php-client/blob/master/src/Storyblok/Client.php#L901) get "enriched".

## Current Behavior

When some resolved relation does have a reference on its own. This reference is not resolved, although the data is returned from the API response.

## Steps to Reproduce

Given relations:
"A" has a reference to "B" and "B" has a reference to "C".

"resolved relations" in the API Request:

"resolved_relations=A.B,B.C"

API response:

```
"uuid": "<uuid of A>"
"content": {
    "B": "<uuid of B>"
 }
"rels": [
  {
    "uuid": "<uuid of B>"
    "content": {
        "C": "<uuid of C>"
     }
  },
  {
    "uuid": "<uuid of C>",
    "content": {...}
  },
]
```

Result:
B is resolved in content A, but C is not resolved in content B.

### PR DESCRIPTION
**Pull request by silasjoisten**
closes #63 #62

### CODE REVIEW

File: src/Resolver/StoryResolver.php [hunk 1]
```diff
@@ -31,21 +31,34 @@ public function resolve(array $target, array $relations): array
             $relationMap[$relation['uuid']] = $relation;
         }
 
-        foreach ($target as &$value) {
-            if (\is_string($value) && \array_key_exists($value, $relationMap)) {
-                $value = $relationMap[$value];
+        return $this->doResolve($target, $relationMap, []);
```
Comment (frastel) [inline src/Resolver/StoryResolver.php:34]: Here are two things done:
- deep resolving of relations
- not to replace the uuids themselves

This would fix my both opened issues. But I think you could simplify this approach a bit.
We have implemented our own StoryResolver in the meantime (I had not enough time yet to create a PR with our version) and we did it like this:

```
        // resolve relations which may be included in the resolved relations themselves
        $this->doResolve($relationMap, $relationMap);

        // resolve relations in the main target
        $this->doResolve($target, $relationMap);

        return $target;
```
and the additional check on the uuid field like its done here.
In this case you do not need the $seen parameter and can assume that the resolved relations are already resolved when the main stories are looped.

Comment (silasjoisten) [reply src/Resolver/StoryResolver.php]: Hey there sorry for the delay i found a more memory saving appoach. if you want to test it feel free.
